Add Multiset/ECMH implementation
kaspanet/secp256k1 pull request #1
Opened 2020-02-17 12:52 UTC by elichai

Hi, the first commit is cherry-picked from https://github.com/Bitcoin-ABC/secp256k1/tree/master/src/modules/multiset
and then I implemented a serliaze/parse functions and fixed wrong docs and some other minor stuff.
Best reviewed commit by commit :)

2020-02-17 13:57 UTC, elichai commented
Travis found a UB in the tests: https://travis-ci.org/kaspanet/secp256k1/jobs/651495050#L391
They cast a unsigned char pointer(alignment: 1) into a uint32_t pointer(alignment 4) which is UB

http://www.iso-9899.info/n1570.html#6.3.2.3p7 [Pointers] A pointer to an object type may be converted to a pointer to a different object type. If the resulting pointer is not correctly aligned) for the referenced type, the behavior is undefined.

2020-02-19 12:03 UTC, stasatdaglabs requested changes

2020-02-19 12:03 UTC, stasatdaglabs commented on include/secp256k1_multiset.h
> +/** Serialize a multiset to bytes
This appears to be a copy+paste error. Please fix.

2020-02-19 12:03 UTC, stasatdaglabs commented on include/secp256k1_multiset.h
> +    const unsigned char *out64
Typo: out64 -> in64

2020-02-19 12:03 UTC, stasatdaglabs commented on src/modules/multiset/main_impl.h
> +/* TODO: Add hash function pointer to optionally replace the hash function */
Please don't leave TODOs inside the code. Instead, create a ticket.

2020-02-19 12:21 UTC, elichai commented on src/modules/multiset/main_impl.h
> +/* TODO: Add hash function pointer to optionally replace the hash function */
Done

2020-02-19 12:21 UTC, elichai commented on include/secp256k1_multiset.h
> +    const unsigned char *out64
Done

2020-02-19 12:21 UTC, elichai commented on include/secp256k1_multiset.h
> +/** Serialize a multiset to bytes
Done

2020-02-19 14:00 UTC, merged